### ISSUE TITLE
Example app broken by 0.5.0

### ISSUE THREAD

**Issue by PJB3005** [jbrd/bevy_mod_imgui#41]
**Describe the bug**
The `hello-world.rs` example no longer works with 0.5.0, giving the following error:

```
thread 'Compute Task Pool (11)' panicked at E:\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.2\src\storage\resource.rs:58:13:
Attempted to access or drop non-send resource bevy_mod_imgui::ImguiContext from thread Some(ThreadId(1)) on a thread ThreadId(21). This is not allowed. Aborting.
```

The extract phase is multithreaded and therefore can't access the ImguiContext safely.

**To Reproduce**
Run `hello-world.rs` with these dependencies:

```rust
bevy = { version = "0.14.2", features = ["dynamic_linking"] }
bevy_mod_imgui = "0.5.0"
imgui = "0.11.0"
```

**Expected behavior**
It not to panic

**Screenshots**
Log above

**Platform (please complete the following information):**
 - Device: PC
 - OS: Windows 11
 - Browser N/A
 - Version 22631.4460

**Additional context**
Going back to 0.4.0 fixes it.

**Comment by jbrd** [comment]
Hi @PJB3005 ,

Thanks for reporting this. Which version of Rust are you using to compile this, and would it be possible to attach your Cargo.lock file so I can see exactly what library dependencies you are using here?

**Comment by jbrd** [comment]
I'd also be interested to see the full call stack of the crash here too...

**Comment by PJB3005** [comment]
You need to enable the `multi_threaded` feature on `bevy` (it's a default feature), then the example in this repo will fail.

**Comment by PJB3005** [comment]
```
E:\Projects\bevy_mod_imgui [main ≡ +0 ~1 -0 !]
> cargo run --example hello-world
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.21s
     Running `target\debug\examples\hello-world.exe`
2024-11-21T14:52:10.122756Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD Radeon RX 6900 XT", vendor: 4098, device: 29631, device_type: DiscreteGpu, driver: "AMD proprietary driver", driver_info: "24.10.1 (AMD proprietary shader compiler)", backend: Vulkan }
2024-11-21T14:52:10.433860Z  INFO bevy_winit::system: Creating new window "App" (Entity { index: 0, generation: 1 })
thread 'Compute Task Pool (8)' panicked at E:\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.2\src\storage\resource.rs:58:13:
Attempted to access or drop non-send resource bevy_mod_imgui::ImguiContext from thread Some(ThreadId(1)) on a thread ThreadId(18). This is not allowed. Aborting.
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\panicking.rs:662
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\panicking.rs:74
   2: bevy_ecs::storage::resource::ResourceData<false>::validate_access<false>
             at E:\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.2\src\storage\resource.rs:58
   3: bevy_ecs::storage::resource::impl$1::get_with_ticks::closure$0<false>
             at E:\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.2\src\storage\resource.rs:114
   4: core::bool::impl$0::then<tuple$<bevy_ptr::Ptr<bevy_ptr::Aligned>,bevy_ecs::component::TickCells>,bevy_ecs::storage::resource::impl$1::get_with_ticks::closure_env$0<false> >
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\core\src\bool.rs:60
   5: bevy_ecs::storage::resource::ResourceData<false>::get_with_ticks<false>
             at E:\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.2\src\storage\resource.rs:113
   6: bevy_ecs::world::unsafe_world_cell::UnsafeWorldCell::get_non_send_resource_mut_by_id
             at E:\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.2\src\world\unsafe_world_cell.rs:508
   7: bevy_ecs::world::unsafe_world_cell::UnsafeWorldCell::get_non_send_resource_mut<bevy_mod_imgui::ImguiContext>
             at E:\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.2\src\world\unsafe_world_cell.rs:480
   8: bevy_ecs::world::World::get_non_send_resource_mut<bevy_mod_imgui::ImguiContext>
             at E:\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.2\src\world\mod.rs:1697
   9: bevy_mod_imgui::imgui_extract_frame_system
             at .\src\lib.rs:722
  10: core::ops::function::FnMut::call_mut<void (*)(bevy_ecs::change_detection::ResMut<bevy_render::MainWorld>,bevy_ecs::change_detection::ResMut<bevy_mod_imgui::ImguiRenderContext>,bevy_ecs::change_detection::ResMut<bevy_render::view::window::ExtractedWindows>,
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\core\src\ops\function.rs:166
  11: core::ops::function::impls::impl$3::call_mut<tuple$<bevy_ecs::change_detection::ResMut<bevy_render::MainWorld>,bevy_ecs::change_detection::ResMut<bevy_mod_imgui::ImguiRenderContext>,bevy_ecs::change_detection::ResMut<bevy_render::view::window::ExtractedWin
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\core\src\ops\function.rs:294
  12: bevy_ecs::system::function_system::impl$20::run::call_inner<tuple$<>,bevy_ecs::change_detection::ResMut<bevy_render::MainWorld>,bevy_ecs::change_detection::ResMut<bevy_mod_imgui::ImguiRenderContext>,bevy_ecs::change_detection::ResMut<bevy_render::view::win
             at E:\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.2\src\system\function_system.rs:710
  13: bevy_ecs::system::function_system::impl$20::run<tuple$<>,void (*)(bevy_ecs::change_detection::ResMut<bevy_render::MainWorld>,bevy_ecs::change_detection::ResMut<bevy_mod_imgui::ImguiRenderContext>,bevy_ecs::change_detection::ResMut<bevy_render::view::window
             at E:\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.2\src\system\function_system.rs:713
  14: bevy_ecs::system::function_system::impl$7::run_unsafe<void (*)(bevy_ecs::change_detection::ResMut<bevy_render::MainWorld>,bevy_ecs::change_detection::ResMut<bevy_mod_imgui::ImguiRenderContext>,bevy_ecs::change_detection::ResMut<bevy_render::view::window::E
             at E:\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.2\src\system\function_system.rs:534
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Encountered a panic in system `bevy_mod_imgui::imgui_extract_frame_system`!
```

**Comment by jbrd** [comment]
Thanks for your contribution - I'll aim to review this today
